// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSettingsByBotID = `-- name: DeleteSettingsByBotID :exec
UPDATE bots
SET max_context_load_time = 1440,
    max_context_tokens = 0,
    max_inbox_items = 50,
    language = 'auto',
    allow_guest = false,
    reasoning_enabled = false,
    reasoning_effort = 'medium',
    heartbeat_enabled = false,
    heartbeat_interval = 30,
    heartbeat_prompt = '',
    chat_model_id = NULL,
    heartbeat_model_id = NULL,
    search_provider_id = NULL,
    memory_provider_id = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DeleteSettingsByBotID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettingsByBotID, id)
	return err
}

const getSettingsByBotID = `-- name: GetSettingsByBotID :one
SELECT
  bots.id AS bot_id,
  bots.max_context_load_time,
  bots.max_context_tokens,
  bots.max_inbox_items,
  bots.language,
  bots.allow_guest,
  bots.reasoning_enabled,
  bots.reasoning_effort,
  bots.heartbeat_enabled,
  bots.heartbeat_interval,
  bots.heartbeat_prompt,
  chat_models.id AS chat_model_id,
  heartbeat_models.id AS heartbeat_model_id,
  search_providers.id AS search_provider_id,
  memory_providers.id AS memory_provider_id
FROM bots
LEFT JOIN models AS chat_models ON chat_models.id = bots.chat_model_id
LEFT JOIN models AS heartbeat_models ON heartbeat_models.id = bots.heartbeat_model_id
LEFT JOIN search_providers ON search_providers.id = bots.search_provider_id
LEFT JOIN memory_providers ON memory_providers.id = bots.memory_provider_id
WHERE bots.id = $1
`

type GetSettingsByBotIDRow struct {
	BotID              pgtype.UUID `json:"bot_id"`
	MaxContextLoadTime int32       `json:"max_context_load_time"`
	MaxContextTokens   int32       `json:"max_context_tokens"`
	MaxInboxItems      int32       `json:"max_inbox_items"`
	Language           string      `json:"language"`
	AllowGuest         bool        `json:"allow_guest"`
	ReasoningEnabled   bool        `json:"reasoning_enabled"`
	ReasoningEffort    string      `json:"reasoning_effort"`
	HeartbeatEnabled   bool        `json:"heartbeat_enabled"`
	HeartbeatInterval  int32       `json:"heartbeat_interval"`
	HeartbeatPrompt    string      `json:"heartbeat_prompt"`
	ChatModelID        pgtype.UUID `json:"chat_model_id"`
	HeartbeatModelID   pgtype.UUID `json:"heartbeat_model_id"`
	SearchProviderID   pgtype.UUID `json:"search_provider_id"`
	MemoryProviderID   pgtype.UUID `json:"memory_provider_id"`
}

func (q *Queries) GetSettingsByBotID(ctx context.Context, id pgtype.UUID) (GetSettingsByBotIDRow, error) {
	row := q.db.QueryRow(ctx, getSettingsByBotID, id)
	var i GetSettingsByBotIDRow
	err := row.Scan(
		&i.BotID,
		&i.MaxContextLoadTime,
		&i.MaxContextTokens,
		&i.MaxInboxItems,
		&i.Language,
		&i.AllowGuest,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.ChatModelID,
		&i.HeartbeatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
	)
	return i, err
}

const upsertBotSettings = `-- name: UpsertBotSettings :one
WITH updated AS (
  UPDATE bots
  SET max_context_load_time = $1,
      max_context_tokens = $2,
      max_inbox_items = $3,
      language = $4,
      allow_guest = $5,
      reasoning_enabled = $6,
      reasoning_effort = $7,
      heartbeat_enabled = $8,
      heartbeat_interval = $9,
      heartbeat_prompt = $10,
      chat_model_id = COALESCE($11::uuid, bots.chat_model_id),
      heartbeat_model_id = COALESCE($12::uuid, bots.heartbeat_model_id),
      search_provider_id = COALESCE($13::uuid, bots.search_provider_id),
      memory_provider_id = COALESCE($14::uuid, bots.memory_provider_id),
      updated_at = now()
  WHERE bots.id = $15
  RETURNING bots.id, bots.max_context_load_time, bots.max_context_tokens, bots.max_inbox_items, bots.language, bots.allow_guest, bots.reasoning_enabled, bots.reasoning_effort, bots.heartbeat_enabled, bots.heartbeat_interval, bots.heartbeat_prompt, bots.chat_model_id, bots.heartbeat_model_id, bots.search_provider_id, bots.memory_provider_id
)
SELECT
  updated.id AS bot_id,
  updated.max_context_load_time,
  updated.max_context_tokens,
  updated.max_inbox_items,
  updated.language,
  updated.allow_guest,
  updated.reasoning_enabled,
  updated.reasoning_effort,
  updated.heartbeat_enabled,
  updated.heartbeat_interval,
  updated.heartbeat_prompt,
  chat_models.id AS chat_model_id,
  heartbeat_models.id AS heartbeat_model_id,
  search_providers.id AS search_provider_id,
  memory_providers.id AS memory_provider_id
FROM updated
LEFT JOIN models AS chat_models ON chat_models.id = updated.chat_model_id
LEFT JOIN models AS heartbeat_models ON heartbeat_models.id = updated.heartbeat_model_id
LEFT JOIN search_providers ON search_providers.id = updated.search_provider_id
LEFT JOIN memory_providers ON memory_providers.id = updated.memory_provider_id
`

type UpsertBotSettingsParams struct {
	MaxContextLoadTime int32       `json:"max_context_load_time"`
	MaxContextTokens   int32       `json:"max_context_tokens"`
	MaxInboxItems      int32       `json:"max_inbox_items"`
	Language           string      `json:"language"`
	AllowGuest         bool        `json:"allow_guest"`
	ReasoningEnabled   bool        `json:"reasoning_enabled"`
	ReasoningEffort    string      `json:"reasoning_effort"`
	HeartbeatEnabled   bool        `json:"heartbeat_enabled"`
	HeartbeatInterval  int32       `json:"heartbeat_interval"`
	HeartbeatPrompt    string      `json:"heartbeat_prompt"`
	ChatModelID        pgtype.UUID `json:"chat_model_id"`
	HeartbeatModelID   pgtype.UUID `json:"heartbeat_model_id"`
	SearchProviderID   pgtype.UUID `json:"search_provider_id"`
	MemoryProviderID   pgtype.UUID `json:"memory_provider_id"`
	ID                 pgtype.UUID `json:"id"`
}

type UpsertBotSettingsRow struct {
	BotID              pgtype.UUID `json:"bot_id"`
	MaxContextLoadTime int32       `json:"max_context_load_time"`
	MaxContextTokens   int32       `json:"max_context_tokens"`
	MaxInboxItems      int32       `json:"max_inbox_items"`
	Language           string      `json:"language"`
	AllowGuest         bool        `json:"allow_guest"`
	ReasoningEnabled   bool        `json:"reasoning_enabled"`
	ReasoningEffort    string      `json:"reasoning_effort"`
	HeartbeatEnabled   bool        `json:"heartbeat_enabled"`
	HeartbeatInterval  int32       `json:"heartbeat_interval"`
	HeartbeatPrompt    string      `json:"heartbeat_prompt"`
	ChatModelID        pgtype.UUID `json:"chat_model_id"`
	HeartbeatModelID   pgtype.UUID `json:"heartbeat_model_id"`
	SearchProviderID   pgtype.UUID `json:"search_provider_id"`
	MemoryProviderID   pgtype.UUID `json:"memory_provider_id"`
}

func (q *Queries) UpsertBotSettings(ctx context.Context, arg UpsertBotSettingsParams) (UpsertBotSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertBotSettings,
		arg.MaxContextLoadTime,
		arg.MaxContextTokens,
		arg.MaxInboxItems,
		arg.Language,
		arg.AllowGuest,
		arg.ReasoningEnabled,
		arg.ReasoningEffort,
		arg.HeartbeatEnabled,
		arg.HeartbeatInterval,
		arg.HeartbeatPrompt,
		arg.ChatModelID,
		arg.HeartbeatModelID,
		arg.SearchProviderID,
		arg.MemoryProviderID,
		arg.ID,
	)
	var i UpsertBotSettingsRow
	err := row.Scan(
		&i.BotID,
		&i.MaxContextLoadTime,
		&i.MaxContextTokens,
		&i.MaxInboxItems,
		&i.Language,
		&i.AllowGuest,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.ChatModelID,
		&i.HeartbeatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
	)
	return i, err
}
