services:
  deps:
    security_opt:
      - label=disable

  migrate:
    security_opt:
      - label=disable

  server:
    security_opt:
      - label=disable

  web:
    security_opt:
      - label=disable
