// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/workspace/bridgepb/bridge.proto

package bridgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecOutput_Stream int32

const (
	ExecOutput_STDOUT ExecOutput_Stream = 0
	ExecOutput_STDERR ExecOutput_Stream = 1
	ExecOutput_EXIT   ExecOutput_Stream = 2
)

// Enum value maps for ExecOutput_Stream.
var (
	ExecOutput_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "EXIT",
	}
	ExecOutput_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"EXIT":   2,
	}
)

func (x ExecOutput_Stream) Enum() *ExecOutput_Stream {
	p := new(ExecOutput_Stream)
	*p = x
	return p
}

func (x ExecOutput_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecOutput_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_workspace_bridgepb_bridge_proto_enumTypes[0].Descriptor()
}

func (ExecOutput_Stream) Type() protoreflect.EnumType {
	return &file_internal_workspace_bridgepb_bridge_proto_enumTypes[0]
}

func (x ExecOutput_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecOutput_Stream.Descriptor instead.
func (ExecOutput_Stream) EnumDescriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{9, 0}
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	LineOffset    int32                  `protobuf:"varint,2,opt,name=line_offset,json=lineOffset,proto3" json:"line_offset,omitempty"`
	NLines        int32                  `protobuf:"varint,3,opt,name=n_lines,json=nLines,proto3" json:"n_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetLineOffset() int32 {
	if x != nil {
		return x.LineOffset
	}
	return 0
}

func (x *ReadFileRequest) GetNLines() int32 {
	if x != nil {
		return x.NLines
	}
	return 0
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TotalLines    int32                  `protobuf:"varint,2,opt,name=total_lines,json=totalLines,proto3" json:"total_lines,omitempty"`
	Binary        bool                   `protobuf:"varint,3,opt,name=binary,proto3" json:"binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *ReadFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReadFileResponse) GetTotalLines() int32 {
	if x != nil {
		return x.TotalLines
	}
	return 0
}

func (x *ReadFileResponse) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{3}
}

type ListDirRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive         bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Offset            int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit             int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	CollapseThreshold int32                  `protobuf:"varint,5,opt,name=collapse_threshold,json=collapseThreshold,proto3" json:"collapse_threshold,omitempty"`
	MaxDepth          int32                  `protobuf:"varint,6,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ListDirRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDirRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDirRequest) GetCollapseThreshold() int32 {
	if x != nil {
		return x.CollapseThreshold
	}
	return 0
}

func (x *ListDirRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       string                 `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FileEntry) GetModTime() string {
	if x != nil {
		return x.ModTime
	}
	return ""
}

func (x *FileEntry) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDirResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDirResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type ExecInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	WorkDir        string                 `protobuf:"bytes,2,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Env            []string               `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	StdinData      []byte                 `protobuf:"bytes,5,opt,name=stdin_data,json=stdinData,proto3" json:"stdin_data,omitempty"`
	Pty            bool                   `protobuf:"varint,6,opt,name=pty,proto3" json:"pty,omitempty"`
	Resize         *TerminalResize        `protobuf:"bytes,7,opt,name=resize,proto3" json:"resize,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecInput) Reset() {
	*x = ExecInput{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInput) ProtoMessage() {}

func (x *ExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInput.ProtoReflect.Descriptor instead.
func (*ExecInput) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *ExecInput) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecInput) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ExecInput) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecInput) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecInput) GetStdinData() []byte {
	if x != nil {
		return x.StdinData
	}
	return nil
}

func (x *ExecInput) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

func (x *ExecInput) GetResize() *TerminalResize {
	if x != nil {
		return x.Resize
	}
	return nil
}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        ExecOutput_Stream      `protobuf:"varint,1,opt,name=stream,proto3,enum=bridgepb.ExecOutput_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *ExecOutput) GetStream() ExecOutput_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecOutput_STDOUT
}

func (x *ExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ReadRawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRawRequest) Reset() {
	*x = ReadRawRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRawRequest) ProtoMessage() {}

func (x *ReadRawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRawRequest.ProtoReflect.Descriptor instead.
func (*ReadRawRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *ReadRawRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRawChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRawChunk) Reset() {
	*x = WriteRawChunk{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRawChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRawChunk) ProtoMessage() {}

func (x *WriteRawChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRawChunk.ProtoReflect.Descriptor instead.
func (*WriteRawChunk) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *WriteRawChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteRawChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRawResponse) Reset() {
	*x = WriteRawResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRawResponse) ProtoMessage() {}

func (x *WriteRawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRawResponse.ProtoReflect.Descriptor instead.
func (*WriteRawResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *WriteRawResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteFileRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{15}
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *FileEntry             `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{17}
}

func (x *StatResponse) GetEntry() *FileEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{18}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{19}
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{20}
}

func (x *RenameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_workspace_bridgepb_bridge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP(), []int{21}
}

var File_internal_workspace_bridgepb_bridge_proto protoreflect.FileDescriptor

const file_internal_workspace_bridgepb_bridge_proto_rawDesc = "" +
	"\n" +
	"(internal/workspace/bridgepb/bridge.proto\x12\bbridgepb\"_\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vline_offset\x18\x02 \x01(\x05R\n" +
	"lineOffset\x12\x17\n" +
	"\an_lines\x18\x03 \x01(\x05R\x06nLines\"e\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vtotal_lines\x18\x02 \x01(\x05R\n" +
	"totalLines\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\bR\x06binary\"@\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x13\n" +
	"\x11WriteFileResponse\"\xbc\x01\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12-\n" +
	"\x12collapse_threshold\x18\x05 \x01(\x05R\x11collapseThreshold\x12\x1b\n" +
	"\tmax_depth\x18\x06 \x01(\x05R\bmaxDepth\"\x93\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\tR\amodTime\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\"\x7f\n" +
	"\x0fListDirResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.bridgepb.FileEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"\xde\x01\n" +
	"\tExecInput\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x19\n" +
	"\bwork_dir\x18\x02 \x01(\tR\aworkDir\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"stdin_data\x18\x05 \x01(\fR\tstdinData\x12\x10\n" +
	"\x03pty\x18\x06 \x01(\bR\x03pty\x120\n" +
	"\x06resize\x18\a \x01(\v2\x18.bridgepb.TerminalResizeR\x06resize\"8\n" +
	"\x0eTerminalResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x9e\x01\n" +
	"\n" +
	"ExecOutput\x123\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1b.bridgepb.ExecOutput.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"*\n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\b\n" +
	"\x04EXIT\x10\x02\"$\n" +
	"\x0eReadRawRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x1f\n" +
	"\tDataChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\rWriteRawChunk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"7\n" +
	"\x10WriteRawResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"E\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x14\n" +
	"\x12DeleteFileResponse\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"9\n" +
	"\fStatResponse\x12)\n" +
	"\x05entry\x18\x01 \x01(\v2\x13.bridgepb.FileEntryR\x05entry\"\"\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x0f\n" +
	"\rMkdirResponse\"E\n" +
	"\rRenameRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"\x10\n" +
	"\x0eRenameResponse2\x88\x05\n" +
	"\x10ContainerService\x12A\n" +
	"\bReadFile\x12\x19.bridgepb.ReadFileRequest\x1a\x1a.bridgepb.ReadFileResponse\x12D\n" +
	"\tWriteFile\x12\x1a.bridgepb.WriteFileRequest\x1a\x1b.bridgepb.WriteFileResponse\x12>\n" +
	"\aListDir\x12\x18.bridgepb.ListDirRequest\x1a\x19.bridgepb.ListDirResponse\x125\n" +
	"\x04Stat\x12\x15.bridgepb.StatRequest\x1a\x16.bridgepb.StatResponse\x128\n" +
	"\x05Mkdir\x12\x16.bridgepb.MkdirRequest\x1a\x17.bridgepb.MkdirResponse\x12;\n" +
	"\x06Rename\x12\x17.bridgepb.RenameRequest\x1a\x18.bridgepb.RenameResponse\x125\n" +
	"\x04Exec\x12\x13.bridgepb.ExecInput\x1a\x14.bridgepb.ExecOutput(\x010\x01\x12:\n" +
	"\aReadRaw\x12\x18.bridgepb.ReadRawRequest\x1a\x13.bridgepb.DataChunk0\x01\x12A\n" +
	"\bWriteRaw\x12\x17.bridgepb.WriteRawChunk\x1a\x1a.bridgepb.WriteRawResponse(\x01\x12G\n" +
	"\n" +
	"DeleteFile\x12\x1b.bridgepb.DeleteFileRequest\x1a\x1c.bridgepb.DeleteFileResponseB6Z4github.com/memohai/memoh/internal/workspace/bridgepbb\x06proto3"

var (
	file_internal_workspace_bridgepb_bridge_proto_rawDescOnce sync.Once
	file_internal_workspace_bridgepb_bridge_proto_rawDescData []byte
)

func file_internal_workspace_bridgepb_bridge_proto_rawDescGZIP() []byte {
	file_internal_workspace_bridgepb_bridge_proto_rawDescOnce.Do(func() {
		file_internal_workspace_bridgepb_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_workspace_bridgepb_bridge_proto_rawDesc), len(file_internal_workspace_bridgepb_bridge_proto_rawDesc)))
	})
	return file_internal_workspace_bridgepb_bridge_proto_rawDescData
}

var file_internal_workspace_bridgepb_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_workspace_bridgepb_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_workspace_bridgepb_bridge_proto_goTypes = []any{
	(ExecOutput_Stream)(0),     // 0: bridgepb.ExecOutput.Stream
	(*ReadFileRequest)(nil),    // 1: bridgepb.ReadFileRequest
	(*ReadFileResponse)(nil),   // 2: bridgepb.ReadFileResponse
	(*WriteFileRequest)(nil),   // 3: bridgepb.WriteFileRequest
	(*WriteFileResponse)(nil),  // 4: bridgepb.WriteFileResponse
	(*ListDirRequest)(nil),     // 5: bridgepb.ListDirRequest
	(*FileEntry)(nil),          // 6: bridgepb.FileEntry
	(*ListDirResponse)(nil),    // 7: bridgepb.ListDirResponse
	(*ExecInput)(nil),          // 8: bridgepb.ExecInput
	(*TerminalResize)(nil),     // 9: bridgepb.TerminalResize
	(*ExecOutput)(nil),         // 10: bridgepb.ExecOutput
	(*ReadRawRequest)(nil),     // 11: bridgepb.ReadRawRequest
	(*DataChunk)(nil),          // 12: bridgepb.DataChunk
	(*WriteRawChunk)(nil),      // 13: bridgepb.WriteRawChunk
	(*WriteRawResponse)(nil),   // 14: bridgepb.WriteRawResponse
	(*DeleteFileRequest)(nil),  // 15: bridgepb.DeleteFileRequest
	(*DeleteFileResponse)(nil), // 16: bridgepb.DeleteFileResponse
	(*StatRequest)(nil),        // 17: bridgepb.StatRequest
	(*StatResponse)(nil),       // 18: bridgepb.StatResponse
	(*MkdirRequest)(nil),       // 19: bridgepb.MkdirRequest
	(*MkdirResponse)(nil),      // 20: bridgepb.MkdirResponse
	(*RenameRequest)(nil),      // 21: bridgepb.RenameRequest
	(*RenameResponse)(nil),     // 22: bridgepb.RenameResponse
}
var file_internal_workspace_bridgepb_bridge_proto_depIdxs = []int32{
	6,  // 0: bridgepb.ListDirResponse.entries:type_name -> bridgepb.FileEntry
	9,  // 1: bridgepb.ExecInput.resize:type_name -> bridgepb.TerminalResize
	0,  // 2: bridgepb.ExecOutput.stream:type_name -> bridgepb.ExecOutput.Stream
	6,  // 3: bridgepb.StatResponse.entry:type_name -> bridgepb.FileEntry
	1,  // 4: bridgepb.ContainerService.ReadFile:input_type -> bridgepb.ReadFileRequest
	3,  // 5: bridgepb.ContainerService.WriteFile:input_type -> bridgepb.WriteFileRequest
	5,  // 6: bridgepb.ContainerService.ListDir:input_type -> bridgepb.ListDirRequest
	17, // 7: bridgepb.ContainerService.Stat:input_type -> bridgepb.StatRequest
	19, // 8: bridgepb.ContainerService.Mkdir:input_type -> bridgepb.MkdirRequest
	21, // 9: bridgepb.ContainerService.Rename:input_type -> bridgepb.RenameRequest
	8,  // 10: bridgepb.ContainerService.Exec:input_type -> bridgepb.ExecInput
	11, // 11: bridgepb.ContainerService.ReadRaw:input_type -> bridgepb.ReadRawRequest
	13, // 12: bridgepb.ContainerService.WriteRaw:input_type -> bridgepb.WriteRawChunk
	15, // 13: bridgepb.ContainerService.DeleteFile:input_type -> bridgepb.DeleteFileRequest
	2,  // 14: bridgepb.ContainerService.ReadFile:output_type -> bridgepb.ReadFileResponse
	4,  // 15: bridgepb.ContainerService.WriteFile:output_type -> bridgepb.WriteFileResponse
	7,  // 16: bridgepb.ContainerService.ListDir:output_type -> bridgepb.ListDirResponse
	18, // 17: bridgepb.ContainerService.Stat:output_type -> bridgepb.StatResponse
	20, // 18: bridgepb.ContainerService.Mkdir:output_type -> bridgepb.MkdirResponse
	22, // 19: bridgepb.ContainerService.Rename:output_type -> bridgepb.RenameResponse
	10, // 20: bridgepb.ContainerService.Exec:output_type -> bridgepb.ExecOutput
	12, // 21: bridgepb.ContainerService.ReadRaw:output_type -> bridgepb.DataChunk
	14, // 22: bridgepb.ContainerService.WriteRaw:output_type -> bridgepb.WriteRawResponse
	16, // 23: bridgepb.ContainerService.DeleteFile:output_type -> bridgepb.DeleteFileResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_workspace_bridgepb_bridge_proto_init() }
func file_internal_workspace_bridgepb_bridge_proto_init() {
	if File_internal_workspace_bridgepb_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_workspace_bridgepb_bridge_proto_rawDesc), len(file_internal_workspace_bridgepb_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_workspace_bridgepb_bridge_proto_goTypes,
		DependencyIndexes: file_internal_workspace_bridgepb_bridge_proto_depIdxs,
		EnumInfos:         file_internal_workspace_bridgepb_bridge_proto_enumTypes,
		MessageInfos:      file_internal_workspace_bridgepb_bridge_proto_msgTypes,
	}.Build()
	File_internal_workspace_bridgepb_bridge_proto = out.File
	file_internal_workspace_bridgepb_bridge_proto_goTypes = nil
	file_internal_workspace_bridgepb_bridge_proto_depIdxs = nil
}
